name: Build on Push

on:
  push:
    branches:
      - main
    paths:
      - "react-reducer/**" # Trigger on changes within this directory

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-reducer # Set working directory for all steps

    steps:
      - name: Check out specific folder
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          # Ensure the sparse-checkout path matches your folder structure
          sparse-checkout: |
            react-reducer

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Run Linting Check
        run: npm run lint

      - name: Run Build
        run: npm run build
